M48
; DRILL file KiCad 10.0.3 date 2026-07-07T17:16:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-07T17:16:14-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X126.5Y-105.5
X129.04Y-105.5
T2
X126.5Y-89.0
X129.0Y-89.0
M30
