//! The grblHAL / Skirnir-conformant postprocessor — Eitri's default dialect.
//!
//! Its output obeys `docs/eitri-gcode-skirnir-contract.md` exactly: the safe preamble `G90 G21 G54 G17 G94`,
//! millimetres, four-decimal coordinates, LF line endings, `M3`/`S`/`M5` spindle, IJK arcs (rendered by the trait
//! default), F on every cut move, no `N` line numbers, and a program that ends with `M2`. Everything the emitter
//! produces routes through the supported-code set, so Skirnir never halts the job on an `error:20`.

use eitri_core::Unit;

use crate::format::{CommentStyle, LineEnding, OutputFormat};
use crate::post::{JobContext, Postprocessor};
use crate::program::Program;

/// The grblHAL-conformant postprocessor. Holds only its formatting config; all motion rendering is the trait default.
#[derive(Debug, Clone)]
pub struct GrblHal {
  format: OutputFormat,
}

impl GrblHal {
  /// A grblHAL postprocessor with the contract's default formatting (mm, four decimals, paren comments, LF).
  pub fn new() -> GrblHal {
    GrblHal {
      format: OutputFormat {
        units: Unit::Millimeters,
        comment_style: CommentStyle::Paren,
        line_ending: LineEnding::Lf,
        ..OutputFormat::default()
      },
    }
  }
}

impl Default for GrblHal {
  fn default() -> GrblHal {
    GrblHal::new()
  }
}

impl Postprocessor for GrblHal {
  fn name(&self) -> &str {
    "grbl"
  }

  fn format(&self) -> OutputFormat {
    self.format
  }

  fn start_code(&self, prog: &mut Program, job: &JobContext) {
    prog.comment("generated by eitri — grblHAL dialect");
    if let Some(name) = &job.name {
      prog.comment(name);
    }
    if let Some(tool) = &job.tool {
      prog.comment(tool);
    }
    // Safe preamble: absolute distance, units, WCS G54, XY plane, units-per-minute feed. Units word tracks the
    // configured unit mode so an inch job emits G20 in the same slot.
    prog.push(format!("G90 {} G54 G17 G94", self.format.units_word()));
  }

  fn end_code(&self, prog: &mut Program, _job: &JobContext) {
    self.spindle_off(prog);
    // M2 resets modal state and ends the program (the contract accepts M2 or M30).
    prog.push("M2");
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn preamble_is_the_safe_contract_preamble() {
    let post = GrblHal::new();
    let mut prog = Program::new(post.format());
    post.start_code(&mut prog, &JobContext { name: Some("isolation".to_string()), tool: None });
    assert!(prog.lines().iter().any(|l| l == "G90 G21 G54 G17 G94"), "lines: {:?}", prog.lines());
    // The header comments are parenthesised.
    assert!(prog.lines().iter().any(|l| l.starts_with('(') && l.contains("eitri")));
  }

  #[test]
  fn program_ends_with_spindle_off_then_m2() {
    let post = GrblHal::new();
    let mut prog = Program::new(post.format());
    post.end_code(&mut prog, &JobContext::default());
    assert_eq!(prog.lines(), &["M5".to_string(), "M2".to_string()]);
  }

  #[test]
  fn inch_units_emit_g20_in_the_preamble() {
    let mut post = GrblHal::new();
    post.format.units = Unit::Inches;
    let mut prog = Program::new(post.format());
    post.start_code(&mut prog, &JobContext::default());
    assert!(prog.lines().iter().any(|l| l == "G90 G20 G54 G17 G94"));
  }
}
