//! A second, deliberately different postprocessor that validates the trait seam.
//!
//! `Generic` is a minimal LinuxCNC-flavoured dialect: semicolon comments, CRLF line endings, three-decimal
//! coordinates, a leaner preamble, and an `M30` program end. It shares every motion/spindle/tool hook with the
//! trait default and overrides only the frame hooks and formatting — proving that swapping controllers is a small,
//! localized change and that the emitter is agnostic to the dialect it drives.

use crate::format::{CommentStyle, LineEnding, OutputFormat};
use crate::post::{JobContext, Postprocessor};
use crate::program::Program;

/// A generic RS-274 postprocessor differing from [`crate::GrblHal`] in comment style, line ending, precision,
/// preamble, and program end — enough to exercise the whole `OutputFormat` + frame-hook surface.
#[derive(Debug, Clone)]
pub struct Generic {
  format: OutputFormat,
}

impl Generic {
  /// A generic postprocessor: semicolon comments, CRLF, three-decimal coordinates.
  pub fn new() -> Generic {
    Generic {
      format: OutputFormat {
        coord_decimals: 3,
        comment_style: CommentStyle::Semicolon,
        line_ending: LineEnding::Crlf,
        ..OutputFormat::default()
      },
    }
  }
}

impl Default for Generic {
  fn default() -> Generic {
    Generic::new()
  }
}

impl Postprocessor for Generic {
  fn name(&self) -> &str {
    "generic"
  }

  fn format(&self) -> OutputFormat {
    self.format
  }

  fn start_code(&self, prog: &mut Program, job: &JobContext) {
    prog.comment("generated by eitri — generic dialect");
    if let Some(name) = &job.name {
      prog.comment(name);
    }
    prog.push(format!("G90 {} G17", self.format.units_word()));
  }

  fn end_code(&self, prog: &mut Program, _job: &JobContext) {
    self.spindle_off(prog);
    prog.push("M30");
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn generic_uses_semicolon_comments_and_crlf() {
    let post = Generic::new();
    let mut prog = Program::new(post.format());
    post.start_code(&mut prog, &JobContext::default());
    assert!(prog.lines().iter().any(|l| l.starts_with("; ")), "lines: {:?}", prog.lines());
    assert!(prog.render().contains("\r\n"));
  }

  #[test]
  fn generic_ends_with_m30() {
    let post = Generic::new();
    let mut prog = Program::new(post.format());
    post.end_code(&mut prog, &JobContext::default());
    assert_eq!(prog.lines().last(), Some(&"M30".to_string()));
  }

  #[test]
  fn generic_renders_three_decimal_coordinates() {
    let post = Generic::new();
    assert_eq!(post.format().coord(1.23456), "1.235");
  }
}
